### ISSUE TITLE
Add styles for toast's `success`, `warning` and `danger`

### ISSUE THREAD

**Issue by ninodinatale** [ninodinatale/creditask-frontend#2]
Toast css classes are already being set in `ToastComponent`, styles are being defined in its `.scss` file, but they aren't being applied somehow.

Colors should be:

```css
.app-toast-success .toast-wrapper {
  background-color: #006F0C;
}

.app-toast-error .toast-wrapper {
  background-color: #6F0004;
}

.app-toast-warning .toast-wrapper {
  background-color: #6F5600;
}

```
